version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false # disable authentication
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.rails
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3001 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      ELASTICSEARCH_URL: http://elasticsearch:9200
      RAILS_ENV: development
    volumes:
      - ./server:/server
    ports:
      - "3001:3001"
    depends_on:
      - db
      - elasticsearch
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.react
    environment:
      REACT_APP_SERVER_URL: http://localhost:3001
    command: npm start
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  postgres-data:
  elasticsearch-data:
