development:
  secret_key_base: <%= Rails.application.credentials.secret_key_base || 'my_secret_key' %>
test:
  secret_key_base: <%= Rails.application.credentials.secret_key_base || 'my_secret_key' %>
